name: Python autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Choose tests set'
        required: true
        type: 'string'
        default: 'smoke'
        options:
          - 'smoke'
          - 'regression'
          - 'all'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.deployment_target }}" == "all" ]; then
            pytest
          elif [ "${{ github.event.inputs.deployment_target }}" == "smoke" ]; then
            pytest -m smoke
          elif [ "${{ github.event.inputs.deployment_target }}" == "regression" ]; then
            pytest -m regression
          else
            echo "Invalid deployment_target specified: ${{ github.event.inputs.deployment_target }}"
            exit 1
          fi
