name: Python autotests with Allure

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: string
        default: smoke
        options:
          - smoke
          - regression
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --alluredir=allure-results
        continue-on-error: true
        env:
          DEPLOYMENT_TARGET: ${{ github.event.inputs.deployment_target }}

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install Allure CLI
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz -O allure-2.24.1.tgz
          sudo tar -zxvf allure-2.24.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.1/bin/allure /usr/local/bin/allure

      - name: Add Executor And Categories in Allure Results
        run: cp -r categories.json executor.json allure-results/

      - name: Generate Allure report
        run: allure generate allure-results -o allure-report --clean

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
          retention-days: 1
